### ISSUE TITLE
Errors in full install step 

### ISSUE THREAD

**Issue by nebuchar** [Appyx/AccessoryServer#2]
Hi,

I'm trying to install AccessoryServer, but I have these errors:

```
pi@raspberrypi:~ $ sudo ./install_full.sh 
sudo: ./install_full.sh: command not found
pi@raspberrypi:~ $ cd AccessoryServer/install/
pi@raspberrypi:~/AccessoryServer/install $ sudo ./install_full.sh 
Welcome! (I hope you started this script with 'sudo' and updated your system)
This program will install all necessary components automatically and will take some time.

Press any key to continue...

installing wiring-pi
Cloning into 'wiringPi'...
remote: Counting objects: 1151, done.
remote: Compressing objects: 100% (957/957), done.
remote: Total 1151 (delta 804), reused 213 (delta 142)
Receiving objects: 100% (1151/1151), 366.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (804/804), done.
wiringPi Build script
=====================


WiringPi Library
[UnInstall]
[Compile] wiringPi.c
[Compile] wiringSerial.c
[Compile] wiringShift.c
[Compile] piHiPri.c
[Compile] piThread.c
[Compile] wiringPiSPI.c
[Compile] wiringPiI2C.c
[Compile] softPwm.c
[Compile] softTone.c
[Compile] mcp23008.c
[Compile] mcp23016.c
[Compile] mcp23017.c
wiringPi.c:1248:21: warning: ‘digitalWrite8Dummy’ defined but not used [-Wunused-function]
 static         void digitalWrite8Dummy       (UNU struct wiringPiNodeStruct *node, UNU int pin, UNU int value) { return ; }
                     ^~~~~~~~~~~~~~~~~~
wiringPi.c:1247:21: warning: ‘digitalRead8Dummy’ defined but not used [-Wunused-function]
 static unsigned int digitalRead8Dummy        (UNU struct wiringPiNodeStruct *node, UNU int UNU pin)            { return 0 ; }
                     ^~~~~~~~~~~~~~~~~
[Compile] mcp23s08.c
[Compile] mcp23s17.c
[Compile] sr595.c
[Compile] pcf8574.c
[Compile] pcf8591.c
[Compile] mcp3002.c
[Compile] mcp3004.c
[Compile] mcp4802.c
[Compile] mcp3422.c
[Compile] max31855.c
[Compile] max5322.c
[Compile] ads1115.c
[Compile] sn3218.c
[Compile] bmp180.c
[Compile] htu21d.c
[Compile] ds18b20.c
[Compile] rht03.c
[Compile] drcSerial.c
[Compile] drcNet.c
[Compile] pseudoPins.c
[Compile] wpiExtensions.c
[Link (Dynamic)]
[Install Headers]
[Install Dynamic Lib]

WiringPi Devices Library
[UnInstall]
[Compile] ds1302.c
[Compile] maxdetect.c
[Compile] piNes.c
[Compile] gertboard.c
[Compile] piFace.c
[Compile] lcd128x64.c
[Compile] lcd.c
[Compile] scrollPhat.c
[Compile] piGlow.c
[Link (Dynamic)]
[Install Headers]
[Install Dynamic Lib]

GPIO Utility
[Compile] gpio.c
[Compile] readall.c
[Compile] pins.c
[Link]
[Install]

All Done.

NOTE: To compile programs with wiringPi, you need to add:
    -lwiringPi
  to your compile line(s) To use the Gertboard, MaxDetect, etc.
  code (the devLib), you need to also add:
    -lwiringPiDev
  to your compile line(s).

Do you want to install the components for transmitting and receiving infrared signals?
Enter 'skip' if you want to skip this step, otherwise press any key.
skip
Do you want to install the components for transmitting and receiving infrared signals?
Enter 'skip' if you want to skip this step, otherwise press any key.
skip 
installing libavahi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavahi-compat-libdnssd-dev is already the newest version (0.6.32-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
installing node

## Installing the NodeSource Node.js v6.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 https://deb.nodesource.com/node_6.x stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease        
Hit:3 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Reading package lists... Done                                 

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_6.x/dists/stretch/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v6.x repo...

+ echo 'deb https://deb.nodesource.com/node_6.x stretch main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_6.x stretch main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 https://deb.nodesource.com/node_6.x stretch InRelease
Hit:2 http://mirrordirector.raspbian.org/raspbian stretch InRelease
Hit:3 http://archive.raspberrypi.org/debian stretch InRelease
Reading package lists... Done

## Run `apt-get install nodejs` (as root) to install Node.js v6.x and npm

Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (6.13.0-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

> serialport@4.0.7 install /home/pi/AccessoryServer/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v48-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@6.13.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/AccessoryServer/node_modules/serialport/.node-gyp"
make: Entering directory '/home/pi/AccessoryServer/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/6.13.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/AccessoryServer/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.14.20-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/AccessoryServer/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/home/pi/AccessoryServer/node_modules/serialport/build/Release"
gyp ERR! cwd /home/pi/AccessoryServer/node_modules/serialport
gyp ERR! node -v v6.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/AccessoryServer/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/home/pi/AccessoryServer/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/AccessoryServer/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 4.14.20-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/AccessoryServer/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/AccessoryServer/node_modules/serialport
node-pre-gyp ERR! node -v v6.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/AccessoryServer/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/home/pi/AccessoryServer/node_modules/serialport/build/Release' (1)
npm WARN hap-server@1.0.1 No repository field.
npm ERR! Linux 4.14.20-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.13.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/AccessoryServer/npm-debug.log
/usr/bin/tsc -> /usr/lib/node_modules/typescript/bin/tsc
/usr/bin/tsserver -> /usr/lib/node_modules/typescript/bin/tsserver
/usr/lib
└── typescript@2.7.2 

Server/HomeKit/AccessoryType.ts(35,23): error TS2339: Property 'HumiditySensor' does not exist on type 'HAPNodeJS'.
installing java
E: Command line option --y is not understood in combination with the other options
rebooting...

```

**Comment by Appyx** [comment]
Hi, the origin of these errors seems to be the serialport library...if you don't want to read in sensor data per Arduino board then it should be safe to ignore the errors.

If it does not work you could try to flash the latest Raspbian Jessie build to fix the errors.
The script is not tested for Raspbian Stretch yet, I will look into it soon :)
